name: Deploy Coinbase Wallet SDK Playground to Pages
true:
  push:
    branches:
    - master
  workflow_dispatch: null
permissions:
  contents: read
  id-token: write
  pages: write
concurrency:
  cancel-in-progress: false
  group: pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install listen.dev
      uses: listendev/action@v1
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: '18'
    - name: Setup Pages
      uses: actions/configure-pages@v3
      with:
        static_site_generator: next
    - name: Install dependencies
      run: yarn install
    - name: Build and export with Next.js
      run: yarn deploy
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./examples/testapp/out
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Install listen.dev
      uses: listendev/action@v1
    - id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
